### ISSUE TITLE
Using a url as service name does not result in a service annoucement

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/jmdns#25]
I am trying to register a service according to the [Physical Web syntax](https://github.com/google/physical-web/blob/master/documentation/mDNS_Support.md):
```
        String service_type = "_http._tcp.";
        String service_name = "http://www.mycompany.com/xyz.html";
        int service_port = 80;
        ServiceInfo service_info = ServiceInfo.create(service_type, service_name, service_port, "");
```
Unfortunately, this service is not properly registered (at least I cannot see it from clients on the network). Changing the name to "xyz" makes it appear.

**Comment by maggu2810** [comment]
IIRC the service name is defined as a domain.
Let's look at the RFC: https://www.ietf.org/rfc/rfc2782.txt
<pre>
   Name
        The domain this RR refers to.  The SRV RR is unique in that the
        name one searches for is not this name; the example near the end
        shows this clearly.
</pre>

Then let's look at: https://www.ietf.org/rfc/rfc1035.txt
<pre>
3. DOMAIN NAME SPACE AND RR DEFINITIONS

3.1. Name space definitions

Domain names in messages are expressed in terms of a sequence of labels.
Each label is represented as a one octet length field followed by that
number of octets.  Since every domain name ends with the null label of
the root, a domain name is terminated by a length byte of zero.  The
high order two bits of every length octet must be zero, and the
remaining six bits of the length field limit the label to 63 octets or
less.

To simplify implementations, the total length of a domain name (i.e.,
label octets and label length octets) is restricted to 255 octets or
less.

Although labels can contain any 8 bit values in octets that make up a
label, it is strongly recommended that labels follow the preferred
syntax described elsewhere in this memo, which is compatible with
existing host naming conventions.  Name servers and resolvers must
compare labels in a case-insensitive manner (i.e., A=a), assuming ASCII
with zero parity.  Non-alphabetic codes must match exactly.
</pre>

There is also stated (I think this is the linked ressources using "the preferred
syntax described elsewhere in this memo"):
<pre>
&lt;domain&gt; ::= &lt;subdomain&gt; | " "

&lt;subdomain&gt; ::= &lt;label&gt; | &lt;subdomain&gt; "." &lt;label&gt;

&lt;label&gt; ::= &lt;letter&gt; [ [ &lt;ldh-str&gt; ] &lt;let-dig&gt; ]

&lt;ldh-str&gt; ::= &lt;let-dig-hyp&gt; | &lt;let-dig-hyp&gt; &lt;ldh-str&gt;

&lt;let-dig-hyp&gt; ::= &lt;let-dig&gt; | "-"

&lt;let-dig&gt; ::= &lt;letter&gt; | &lt;digit&gt;

&lt;letter&gt; ::= any one of the 52 alphabetic characters A through Z in
upper case and a through z in lower case

&lt;digit&gt; ::= any one of the ten digits 0 through 9
</pre>

So, I believe that the characters ':' and '/' are not accepted by JmDNS.

A look at the source will perhaps make it more clear... Let's check it.
But IMHO it is okay, if this is not working with the current code base.

**Comment by kaikreuzer** [comment]
I think what rfc2782 refers to as "name" is the very last part of the service_type, which would be in full length ""_http._tcp.local." - where the domain name is "local". The service name is what is put as a prefix and it usually should allow these characters.

**Comment by maggu2810** [comment]
wireshark shows the message, but the format is perhaps wrong of the raw message.
I have written a DNS SRV message generator and parser (C++) already, perhaps I can try generating such a message myself and parse the JmDNS generated one.

**Comment by kaikreuzer** [comment]
Thanks for your support! FTR: You can use the apps https://play.google.com/store/apps/details?id=physical_web.org.physicalweb&hl=de and https://itunes.apple.com/us/app/physical-web/id927653608?mt=8 to really make sure that the services are announced as expected.

**Comment by maggu2810** [comment]
The app in the Google Play Store does not fit to the current master on Github (MdnsUrlDiscoverer instead of MdnsPwoDiscoverer).
If I read https://github.com/google/physical-web/issues/289 (and the issue 414) I do not think the format that is used for mDNS is already well defined.

The RFC for a DNS SRV RR still states
<pre>
   Here is the format of the SRV RR, whose DNS type code is 33:
        _Service._Proto.Name TTL Class SRV Priority Weight Port Target
</pre>

So I would still prefer they are using a well defined service for physical web and define the URL in a text record only.
Also wireshark does not split service proto and name very well.

So, sorry but I do not think I will further investigate this one.

Do you know why they decided to use a physical web service name and add the remaining information to text records?

**Comment by kaikreuzer** [comment]
Thanks again, @maggu2810 - I think you are right and I should rather close this issue for the moment then...

**Comment by cco3** [comment]
> So I would still prefer they are using a well defined service for physical web and define the URL in a text record only.

This sounds reasonable.  I admit I'm largely ignorant about mDNS.  Could you offer a few reasons why we should do this?

**Comment by kaikreuzer** [comment]
@maggu2810, did you see the question?

**Comment by maggu2810** [comment]
I already referenced the RFC above.
You are using existing stuff that is already specified.
If you want to use the the service discovery through multicast DNS, you have to use it in a way, that is compliant to the existing specifications.
Just do it right ;-)

If I'm honest, I do not think we have to find some other reasons then not violating the fundamental concepts of the DNS infrastructure.

**Comment by maggu2810** [comment]
Perhaps I do not understand the specifications / RFCs correctly... this is also possible. ;-)

**Comment by maggu2810** [comment]
Also look at this https://tools.ietf.org/html/rfc6763#page-6

What you normally do is browsing (search) for services of special types (e.g. physical web), so we search for a type.
This would be possible if you use a service and not if we fill a URL in the specific field.

**Comment by maggu2810** [comment]
Well known services: http://www.dns-sd.org/servicetypes.html

**Comment by cco3** [comment]
Please take a look at this pull request and let me know if this is what you are describing or if I'm misunderstanding:
https://github.com/google/physical-web/pull/492
